export const DASHBOARD_PAGE = '/dashboard'
export const LOGIN_PAGE = '/'
export const HOME = '/'
export const NOT_FOUND = '/404'
export const TEXT = 'TEXT'
export const DATE = 'DATE'
export const IMAGE = 'IMAGE'
export const AVATAR = 'AVATAR'
export const POPOVER = 'POPOVER'

export const CREATED_AT = 'createdAt'
export const EMAIL = 'email'
export const DISPLAY_NAME = 'displayName'
export const SIGNED_UP_DATE = 'signedUpDate'
export const FIRST_LOGIN = 'firstLogin'
export const HEADER = 'Header'
export const FOOTER = 'Footer'

export const INITIAL_SCREEN = 'INITIAL_SCREEN'
export const BAD_FILE_SCREEN = 'BAD_FILE_SCREEN'
export const SERVER_ERROR_SCREEN = 'SERVER_ERROR_SCREEN'
export const REPORT_SCREEN = 'REPORT_SCREEN'
export const LOADING_SCREEN = 'LOADING_SCREEN'

export const PASSWORD = 'PASSWORD'
export const CONFIRM_PASSWORD = 'CONFIRM_PASSWORD'

export const RESET_STATE = {}

export const RESET_PASSWORD = 'resetPassword'
export const RECOVER_EMAIL = 'recoverEmail'
export const VERIFY_EMAIL = 'verifyEmail'
export const REJECTED = 'Rejected'
export const LOADING = 'Loading'
export const ERROR = 'Error'
export const INITIAL = 'Initial'
export const SUCCESS = 'Success'
