export const GET_EXPERTS = 'GET_EXPERTS'
export const GET_EXPERTS_PENDING = 'GET_EXPERTS_PENDING'
export const GET_EXPERTS_FULFILLED = 'GET_EXPERTS_FULFILLED'
export const GET_EXPERTS_REJECTED = 'GET_EXPERTS_REJECTED'

export const GET_USER = 'GET_USER'
export const GET_USER_PENDING = 'GET_USER_PENDING'
export const GET_USER_FULFILLED = 'GET_USER_FULFILLED'
export const GET_USER_REJECTED = 'GET_USER_REJECTED'

export const SET_USER = 'SET_USER'
export const SET_USER_PENDING = 'SET_USER_PENDING'
export const SET_USER_FULFILLED = 'SET_USER_FULFILLED'
export const SET_USER_REJECTED = 'SET_USER_REJECTED'

export const GET_INVITATIONS = 'GET_INVITATIONS'
export const GET_INVITATIONS_PENDING = 'GET_INVITATIONS_PENDING'
export const GET_INVITATIONS_FULFILLED = 'GET_INVITATIONS_FULFILLED'
export const GET_INVITATIONS_REJECTED = 'GET_INVITATIONS_REJECTED'

export const GET_MORE_INVITATIONS = 'GET_MORE_INVITATIONS'
export const GET_MORE_INVITATIONS_PENDING = 'GET_MORE_INVITATIONS_PENDING'
export const GET_MORE_INVITATIONS_FULFILLED = 'GET_MORE_INVITATIONS_FULFILLED'
export const GET_MORE_INVITATIONS_REJECTED = 'GET_MORE_INVITATIONS_REJECTED'

export const GET_ACTIVE_USERS = 'GET_ACTIVE_USERS'
export const GET_ACTIVE_USERS_PENDING = 'GET_ACTIVE_USERS_PENDING'
export const GET_ACTIVE_USERS_FULFILLED = 'GET_ACTIVE_USERS_FULFILLED'
export const GET_ACTIVE_USERS_REJECTED = 'GET_ACTIVE_USERS_REJECTED'

export const GET_MORE_ACTIVE_USERS = 'GET_MORE_ACTIVE_USERS'
export const GET_MORE_ACTIVE_USERS_PENDING = 'GET_MORE_ACTIVE_USERS_PENDING'
export const GET_MORE_ACTIVE_USERS_FULFILLED = 'GET_MORE_ACTIVE_USERS_FULFILLED'
export const GET_MORE_ACTIVE_USERS_REJECTED = 'GET_MORE_ACTIVE_USERS_REJECTED'

export const GET_OVERVIEW = 'GET_OVERVIEW'
export const GET_OVERVIEW_PENDING = 'GET_OVERVIEW_PENDING'
export const GET_OVERVIEW_FULFILLED = 'GET_OVERVIEW_FULFILLED'
export const GET_OVERVIEW_REJECTED = 'GET_OVERVIEW_REJECTED'
