export const LOG_OUT = 'LOG_OUT'
export const LOG_OUT_PENDING = 'LOG_OUT_PENDING'

export const LOG_IN = 'LOG_IN'
export const LOG_IN_FULFILLED = 'LOG_IN_FULFILLED'
export const LOG_IN_REJECTED = 'LOG_IN_REJECTED'
export const LOG_IN_PENDING = 'LOG_IN_PENDING'
export const LOG_OUT_REJECTED = 'LOG_OUT_REJECTED'
export const LOG_OUT_FULFILLED = 'LOG_OUT_FULFILLED'
