export const LOG_OUT = 'LOG_OUT'

export const GET_EXPERTS = 'GET_EXPERTS'
export const GET_EXPERTS_PENDING = 'GET_EXPERTS_PENDING'
export const GET_EXPERTS_FULFILLED = 'GET_EXPERTS_FULFILLED'
export const GET_EXPERTS_REJECTED = 'GET_EXPERTS_REJECTED'

export const GET_USER = 'GET_USER'
export const GET_USER_PENDING = 'GET_USER_PENDING'
export const GET_USER_FULFILLED = 'GET_USER_FULFILLED'
export const GET_USER_REJECTED = 'GET_USER_REJECTED'

export const GET_INVITATIONS = 'GET_INVITATIONS'
export const GET_INVITATIONS_PENDING = 'GET_INVITATIONS_PENDING'
export const GET_INVITATIONS_FULFILLED = 'GET_INVITATIONS_FULFILLED'
export const GET_INVITATIONS_REJECTED = 'GET_INVITATIONS_REJECTED'

export const GET_MORE_INVITATIONS = 'GET_MORE_INVITATIONS'
export const GET_MORE_INVITATIONS_PENDING = 'GET_MORE_INVITATIONS_PENDING'
export const GET_MORE_INVITATIONS_FULFILLED = 'GET_MORE_INVITATIONS_FULFILLED'
export const GET_MORE_INVITATIONS_REJECTED = 'GET_MORE_INVITATIONS_REJECTED'

export const GET_ACTIVE_USERS = 'GET_ACTIVE_USERS'
export const GET_ACTIVE_USERS_PENDING = 'GET_ACTIVE_USERS_PENDING'
export const GET_ACTIVE_USERS_FULFILLED = 'GET_ACTIVE_USERS_FULFILLED'
export const GET_ACTIVE_USERS_REJECTED = 'GET_ACTIVE_USERS_REJECTED'

export const GET_MORE_ACTIVE_USERS = 'GET_MORE_ACTIVE_USERS'
export const GET_MORE_ACTIVE_USERS_PENDING = 'GET_MORE_ACTIVE_USERS_PENDING'
export const GET_MORE_ACTIVE_USERS_FULFILLED = 'GET_MORE_ACTIVE_USERS_FULFILLED'
export const GET_MORE_ACTIVE_USERS_REJECTED = 'GET_MORE_ACTIVE_USERS_REJECTED'

export const GET_OVERVIEW = 'GET_OVERVIEW'
export const GET_OVERVIEW_PENDING = 'GET_OVERVIEW_PENDING'
export const GET_OVERVIEW_FULFILLED = 'GET_OVERVIEW_FULFILLED'
export const GET_OVERVIEW_REJECTED = 'GET_OVERVIEW_REJECTED'

export const GET_QUESTIONS = 'GET_QUESTIONS'
export const GET_QUESTIONS_PENDING = 'GET_QUESTIONS_PENDING'
export const GET_QUESTIONS_FULFILLED = 'GET_QUESTIONS_FULFILLED'
export const GET_QUESTIONS_REJECTED = 'GET_QUESTIONS_REJECTED'

export const GET_MORE_QUESTIONS = 'GET_MORE_QUESTIONS'
export const GET_MORE_QUESTIONS_PENDING = 'GET_MORE_QUESTIONS_PENDING'
export const GET_MORE_QUESTIONS_FULFILLED = 'GET_MORE_QUESTIONS_FULFILLED'
export const GET_MORE_QUESTIONS_REJECTED = 'GET_MORE_QUESTIONS_REJECTED'

export const GET_APPOINTMENTS = 'GET_APPOINTMENTS'
export const GET_APPOINTMENTS_PENDING = 'GET_APPOINTMENTS_PENDING'
export const GET_APPOINTMENTS_FULFILLED = 'GET_APPOINTMENTS_FULFILLED'
export const GET_APPOINTMENTS_REJECTED = 'GET_APPOINTMENTS_REJECTED'

export const GET_MORE_APPOINTMENTS = 'GET_MORE_APPOINTMENTS'
export const GET_MORE_APPOINTMENTS_PENDING = 'GET_MORE_APPOINTMENTS_PENDING'
export const GET_MORE_APPOINTMENTS_FULFILLED = 'GET_MORE_APPOINTMENTS_FULFILLED'
export const GET_MORE_APPOINTMENTS_REJECTED = 'GET_MORE_APPOINTMENTS_REJECTED'

export const GET_SIGN_UPS = 'GET_SIGN_UPS'
export const GET_SIGN_UPS_PENDING = 'GET_SIGN_UPS_PENDING'
export const GET_SIGN_UPS_FULFILLED = 'GET_SIGN_UPS_FULFILLED'
export const GET_SIGN_UPS_REJECTED = 'GET_SIGN_UPS_REJECTED'

export const GET_ORGANIZATION = 'GET_ORGANIZATION'
export const GET_ORGANIZATION_PENDING = 'GET_ORGANIZATION_PENDING'
export const GET_ORGANIZATION_FULFILLED = 'GET_ORGANIZATION_FULFILLED'
export const GET_ORGANIZATION_REJECTED = 'GET_ORGANIZATION_REJECTED'

export const GET_ENTITIES = 'GET_ENTITIES'
export const GET_ENTITIES_PENDING = 'GET_ENTITIES_PENDING'
export const GET_ENTITIES_FULFILLED = 'GET_ENTITIES_FULFILLED'
export const GET_ENTITIES_REJECTED = 'GET_ENTITIES_REJECTED'

export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_PENDING = 'UPDATE_USER_PENDING'
export const UPDATE_USER_FULFILLED = 'UPDATE_USER_FULFILLED'
export const UPDATE_USER_REJECTED = 'UPDATE_USER_REJECTED'
