import { intl } from 'src/i18n'
import { ERROR } from '../firebase/constants'

export const PARSE_CSV_ERROR = {
	MISSING_FILE: 'Please provide a valid file',
	FAILED_PARSING: 'Failed parsing object to file.',
	BAD_FILE:
		'Please verify the file format and layout. We recommend that you download and use the sample file to prevent further issues.'
}

export const FIREBASE_ERROR = {
	[ERROR.INSUFICIENT_PERMISSION]: intl.insuficientPermission.description,
	[ERROR.INVALID_EMAIL]: intl.invalidEmail.description,
	[ERROR.WRONG_PASSWORD]: intl.wrongPassword.description,
	[ERROR.USER_NOT_FOUND]: intl.userNotFound.description,
	[ERROR.TOO_MANY_REQUESTS]: intl.tooManyRequest.description,
	[ERROR.USER_PROFILE_NOT_FOUND]: intl.userProfileNotFound.description,
	[ERROR.EXPIRED_ACTION_CODE]: intl.expiredActionCode.description,
	[ERROR.INVALID_ACTION_CODE]: intl.invalidaActionCode.description,
	[ERROR.USER_DISABLED]: intl.userDisabled.description,
	[ERROR.PASSWORDS_MISMATCH]: intl.passwordsMismatch.description,
	[ERROR.WEAK_PASSWORD]: intl.weakPassword.description,
	[ERROR.INTERNAL_ERROR]: intl.internalError.description,
	[ERROR.EMAIL_ALREADY_IN_USE]: intl.emailAlreadyInUse.description,
	[ERROR.EMAIL_ALREADY_EXISTS]: intl.emailAlreadyExists.description,
	[ERROR.INVALID_CREDENTIAL]: intl.invalidCredential.description,
	[ERROR.INVALID_PASSWORD]: intl.invalidPassword.description,
	[ERROR.CLAIMS_TOO_LARGE]: 'missing error description',
	[ERROR.ID_TOKEN_EXPIRED]: 'missing error description',
	[ERROR.ID_TOKEN_REVOKED]: 'missing error description',
	[ERROR.INVALID_ARGUMENT]: 'missing error description',
	[ERROR.INVALID_CLAIMS]: 'missing error description',
	[ERROR.INVALID_CONTINUE_URL]: 'missing error description',
	[ERROR.INVALID_CREATION_TIME]: 'missing error description',
	[ERROR.INVALID_DISABLED_FIELD]: 'missing error description',
	[ERROR.INVALID_DISPLAY_NAME]: 'missing error description',
	[ERROR.INVALID_DYNAMIC_LINK_DOMAIN]: 'missing error description',
	[ERROR.INVALID_HASH_ALGORITHM]: 'missing error description',
	[ERROR.INVALID_HASH_BLOCK_SIZE]: 'missing error description',
	[ERROR.INVALID_HASH_DERIVED_KEY_LENGTH]: 'missing error description',
	[ERROR.INVALID_HASH_KEY]: 'missing error description',
	[ERROR.INVALID_HASH_MEMORY_COST]: 'missing error description',
	[ERROR.INVALID_HASH_PARALLELIZATION]: 'missing error description',
	[ERROR.INVALID_HASH_ROUNDS]: 'missing error description',
	[ERROR.INVALID_HASH_SALT_SEPARATOR]: 'missing error description',
	[ERROR.INVALID_ID_TOKEN]: 'missing error description',
	[ERROR.INVALID_LAST_SIGN_IN_TIME]: 'missing error description',
	[ERROR.INVALID_PAGE_TOKEN]: 'missing error description',
	[ERROR.INVALID_PASSWORD_HASH]: 'missing error description',
	[ERROR.INVALID_PASSWORD_SALT]: 'missing error description',
	[ERROR.INVALID_PHONE_NUMBER]: 'missing error description',
	[ERROR.INVALID_PHOTO_URL]: 'missing error description',
	[ERROR.INVALID_PROVIDER_DATA]: 'missing error description',
	[ERROR.INVALID_PROVIDER_ID]: 'missing error description',
	[ERROR.INVALID_SESSION_COOKIE_DURATION]: 'missing error description',
	[ERROR.INVALID_UID]: 'missing error description',
	[ERROR.INVALID_USER_IMPORT]: 'missing error description',
	[ERROR.MAXIMUM_USER_COUNT_EXCEEDED]: 'missing error description',
	[ERROR.MISSING_ANDROID_PKG_NAME]: 'missing error description',
	[ERROR.MISSING_CONTINUE_URI]: 'missing error description',
	[ERROR.MISSING_HASH_ALGORITHM]: 'missing error description',
	[ERROR.MISSING_IOS_BUNDLE_ID]: 'missing error description',
	[ERROR.MISSING_UID]: 'missing error description',
	[ERROR.OPERATION_NOT_ALLOWED]: 'missing error description',
	[ERROR.PHONE_NUMBER_ALREADY_EXISTS]: 'missing error description',
	[ERROR.PROJECT_NOT_FOUND]: 'missing error description',
	[ERROR.RESERVED_CLAIMS]: 'missing error description',
	[ERROR.SESSION_COOKIE_EXPIRED]: 'missing error description',
	[ERROR.SESSION_COOKIE_REVOKED]: 'missing error description',
	[ERROR.UID_ALREADY_EXISTS]: 'missing error description',
	[ERROR.UNAUTHORIZED_CONTINUE_URI]: 'missing error description'
}
